### ISSUE TITLE
[FEAT] Add clear SteamOS version parity for image tags

### ISSUE THREAD

**Issue by spkane** [linuxserver/docker-steamos#12]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Add image tags that directly map to the SteamOS version that the container includes.

_e.g._ `ghcr.io/linuxserver/steamos:3.5.7`

On SteamOS, the `/etc/os-release` file looks like this:

```
NAME="SteamOS"
PRETTY_NAME="SteamOS"
VERSION_CODENAME=holo
ID=steamos
ID_LIKE=arch
ANSI_COLOR="1;35"
HOME_URL="https://www.steampowered.com/"
DOCUMENTATION_URL="https://support.steampowered.com/"
SUPPORT_URL="https://support.steampowered.com/"
BUG_REPORT_URL="https://support.steampowered.com/"
LOGO=steamos
VARIANT_ID=steamdeck
VERSION_ID=3.5.7
BUILD_ID=20231122.1
```

Using at least the VERSION_ID in the tag would be very useful, although I could also imagine using the ID-VARIANT_ID-VERSION_ID (and even the BUILD_ID) depending on how many variants are maintained.

### Reason for change

I think that this image could be an excellent basis for developing applications for the SteamDeck (especially when paired with `distrobox`), and I would love to be able to determine easily the container release that matches the current release of SteamOS that I have installed on my SteamDeck, so that the library version and what not will match up properly.

### Proposed code change

In theory, this would only require improving the CI/CD pipeline to include these tags, but to be really useful it might also require building this image for a few versions of SteamOS so that people can choose from the one that they require.

**Comment by aptalca** [comment]
Unfortunately that's not possible. The image tags are tied to the [external triggers](https://github.com/linuxserver/docker-steamos/blob/master/.github/workflows/external_trigger.yml). Since this image is based on arch, a rolling distro, and it's using a baseimage, we have to tie the image builds to baseimage builds, otherwise they go out of sync and builds fail.

The tag that is being used is the tag the baseimage uses so whenever the baseimage builds (weekly), the downstream images will trigger within the hour.

This is only the case for our arch baseimage. We do not have such issues on ubuntu, debian or alpine so those ones can use proper external tags and the builds do not have to be coupled to baseimage builds.
